# Generated by Django 3.0.2 on 2020-01-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(default='None', upload_to='', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.TextField(max_length=50, verbose_name='Название вакансии')),
                ('short_job_name', models.TextField(max_length=50, verbose_name='Краткое название вакансии')),
                ('loacation', models.TextField(max_length=50, verbose_name='Местонахождение')),
                ('hot', models.BooleanField(default=False, verbose_name='Hot')),
                ('body', models.TextField(default='', verbose_name='Описание')),
                ('tags', models.ManyToManyField(to='first_app.Tags', verbose_name='Теги')),
            ],
            options={
                'ordering': ('hot',),
            },
        ),
    ]
